[package]
name = "i3-focus-last"
version = "0.2.2"
authors = ["lbonn"]
description = "Focus last window on i3"
license = "MIT"
repository = "https://github.com/lbonn/i3-focus-last"

[dependencies]
i3ipc = "0.9.0"
clap = "2.32.0"
rmp-serde = "0.13.7"
serde = "1.0.80"
serde_derive = "1.0.80"
