[package]
name = "i3-focus-last"
version = "0.3.1"
authors = ["lbonn"]
description = "Focus last window on i3"
license = "MIT"
repository = "https://github.com/lbonn/i3-focus-last"

[dependencies]
i3ipc = "0.10.0"
clap = "2.32.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
